[package]
name = "stocker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.136"
serde_derive = "1.0.136"
r2d2 = "0.8.9"
actix-web = "4.0.1"
toml = "0.5.8"
chrono = "0.4.19"

[dependencies.diesel]
version = "1.4.8"
features = ["postgres", "r2d2", "chrono"]
default-features = false
